labo_home_home:
    pattern:  /
    defaults: { _controller: AcmeGroupLaboBundle:Labo:home }

labo_home:
    pattern:  /home/{option}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:home, option: null }

labo_working:
    pattern:  /encours
    defaults: { _controller: AcmeGroupLaboBundle:Labo:working }

## page listing entités images par type
labo_page_imageByType:
    pattern:  /labo-entite/{action}/image.{classEntite}/{element}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:imageByType, action: "liste", element: null }

## page listing entités
labo_page_entite:
    pattern:  /labo-entite/{action}/{classEntite}/{element}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:entite, action: "liste", element: null }

## page listing Users
labo_page_User:
    pattern:  /labo-users/{action}/{role}/{element}.{changeRole}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:User, action: "liste", role: 'tous-roles', element: 'all', changeRole: null }

## Actions sur paramètres
labo_parametre_action:
    pattern:  /labo-parametres/{action}/{groupe}/{paramSlug}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:editParametres, action: "liste", groupe: "all", paramSlug: null }

## Actions sur entités
labo_entite_action:
    pattern:  /labo-action/{action}/{classEntite}/{id}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:actionEntite }

labo_entite_save:
    pattern:  /save-entite/{entiteNom}/{id}/{champ}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:saveEntite }

labo_entite_get:
    pattern:  /get-entite/{entiteNom}/{id}/{champ}/{short}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:getEntite, short: null }

labo_entite_htmlget:
    pattern:  /gethtml-entite/{entiteNom}/{id}/{champ}/{short}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:getHtmlEntite, short: null }

## articles
labo_page_noteEntite:
    pattern:  /labo-note-article/{classEntite}/{id}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:noteEntite, id: null }

labo_page_vente:
    pattern:  /labo-vente-article/{type}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:VenteArticle, type: 'all' }

labo_page_venteaction:
    pattern:  /labo-vente-action/{id}/{action}/{comefrom}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:VenteAction, comefrom: null }

## BLOCS pour mise à jour Ajax
listeEntiteLigne:
    pattern:  /ajaxUpdate/lignes/{classEntite}/{id}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:listeEntiteLigne }

## ADMIN exports (CSV, etc.)
labo_export_cvs_vente:
    pattern:  /labo-export/csv/{type}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:getCSVvente, type: 'all' }


## STATISTIQUES statistiquesIp
labo_stats_generic:
    pattern:  /labo-statistiques/{stat}/{details}
    defaults: { _controller: AcmeGroupLaboBundle:Aelog:statistiques, stat: 'general', details: null }

labo_stats_suiviIP:
    pattern:  /labo-statistiques-ip/{ip}/{dateDebut}/{dateFin}
    defaults: { _controller: AcmeGroupLaboBundle:Aelog:statistiquesIp, dateDebut: null, dateFin: null }

labo_stats_page:
    pattern:  /labo-statistiques-pages/{pageSlug}/{dateDebut}/{dateFin}
    defaults: { _controller: AcmeGroupLaboBundle:Aelog:statistiquesPage, dateDebut: null, dateFin: null }

labo_stats_articles:
    pattern:  /labo-statistiques-article/{articleSlug}/{dateDebut}/{dateFin}
    defaults: { _controller: AcmeGroupLaboBundle:Aelog:statArticles, dateDebut: null, dateFin: null }

labo_stats_graphiques:
    pattern:  /labo-statistiques-graphiques/{data}
    defaults: { _controller: AcmeGroupLaboBundle:Aelog:graphLinePlot, data: null }


#############################
## SUPER ADMIN
#############################

labo_page_routes:
    pattern:  /sadmin/show-routes/{motif}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:showRoutes, motif: "acme_site_" }

labo_page_database:
    pattern:  /sadmin/show-database/{classEntite}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:showDatabase, classEntite: null }

labo_page_database_field:
    pattern:  /sadmin/show-fields/{classEntite}/{champ}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:showField }

labo_richtext_links:
    pattern:  /sadmin/richtext-links/{id}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:richtextLinks, id: null }

labo_images_version:
    pattern:  /sadmin/images-version/{id}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:imagesVersion, id: null }

## SUPER ADMIN CHECKS
labo_check_database:
    pattern:  /sadmin/checking/{entite}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:checking }

## SUPER ADMIN GENERATE RANDOM DATA
labo_generate_random_data:
    pattern:  /sadmin/generate-random-data/{entite}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:generateRandomData }


