parameters:
# acme_group_labo.example.class: labo\Bundle\TestmanuBundle\Example

services:

    ###################################
    ### OUTILS GÉNÉRIQUES
    ###################################

    # Fonctions textes utiles et pratiques pour utilisation dans TWIG
    acmeGroup.textutilities:
        class: labo\Bundle\TestmanuBundle\services\aetools\twigAetools
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    # Fonctionnalités sur les textes (notamment l'entité richtext)
    acmeGroup.texttools:
        class: labo\Bundle\TestmanuBundle\services\aetools\richtextsAetools
        arguments: [@service_container]

    # Fonctionnalités de requêtes et dossiers/fichiers
    acmeGroup.aetools:
        class: labo\Bundle\TestmanuBundle\services\aetools\aetools
        arguments: [@service_container]

    # Fonctionnalités de dates/heures
    acmeGroup.aedates:
        class: labo\Bundle\TestmanuBundle\services\aetools\aedates
        arguments: [@service_container]

    # Fonctionnalités de parametres du site
    acmeGroup.parametre:
        class: labo\Bundle\TestmanuBundle\services\aetools\parametre
        arguments: [@service_container]

    # Fonctionnalités de manipulations d'images
    acmeGroup.imagetools:
        class: labo\Bundle\TestmanuBundle\services\aetools\imageAetools
        arguments: [@service_container]

    # Fonctionnalités de parsage XML
    acmeGroup.XMLparser:
        class: labo\Bundle\TestmanuBundle\services\aetools\XMLparser
        arguments: []

    ###################################
    ### OUTILS ENTITÉS
    ###################################

    # Fonctionnalités de base pour les entités
    acmeGroup.entities:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\entitiesGeneric
        arguments: [@service_container]

    # Fonctionnalités de gestion des versions (sociétés)
    acmeGroup.version:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\version
        arguments: [@service_container]

    # Fonctionnalités de gestion des pages web
    acmeGroup.pageweb:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\pageweb
        arguments: [@service_container]

    # Fonctionnalités de gestion des collections
    acmeGroup.collection:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\collection
        arguments: [@service_container]

    # Fonctionnalités de gestion des votes
    acmeGroup.votes:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\votes
        arguments: [@service_container]

    # Fonctionnalités de gestion des visites sur le site
    acmeGroup.visite:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\visite
        arguments: [@service_container]

    # Fonctionnalités de categorie
    acmeGroup.categorie:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\categorie
        arguments: [@service_container]

    # Fonctionnalités pour articles
    acmeGroup.article:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\article
        arguments: [@service_container]

    # Atelier créatif et fiches
    acmeGroup.atelierCreatif:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\atelierCreatif
        arguments: [@service_container]

    # magasins
    acmeGroup.magasin:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\magasin
        arguments: [@service_container]

    # videos
    acmeGroup.video:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\video
        arguments: [@service_container]

    # évènements
    acmeGroup.events:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\evenement
        arguments: [@service_container]

    # presse
    acmeGroup.presse:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\presse
        arguments: [@service_container]

    # factures
    acmeGroup.facture:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\facture
        arguments: [@service_container]

    # aelogs
    acmeGroup.aelog:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\aelog
        arguments: [@service_container]

    # Fonctionnalités de gestion du panier d'achat
    # -> synthèses, ajouts, suppressions, etc. de produits dans le panier
    acmeGroup.panier:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\panier
        arguments: [@service_container]
        # scope: request

    acmeGroup.directeditor:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\directeditor
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    ###################################
    ### EVENT LISTENER AU DÉMARRAGE DE REQUETE PRINCIPALE
    ###################################

    # EventListerner sur paramètres généraux du site
    acmeGroup.site_listener:
        class: labo\Bundle\TestmanuBundle\eventListeners\siteListener\siteListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: load_session_items }


    ###################################
    ### EVENT LISTENER SUR DOCTRINE ENTITIES
    ###################################

    # Utilitaire de gestion sur les entités
    acmeGroup.entityUtils:
        class: labo\Bundle\TestmanuBundle\services\entitiesServices\entityListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postRemove }


    ###################################
    ### OUTILS FIXTURES
    ###################################

    # Fixtures : fixturesLoader
    acmeGroup.fixturesLoader:
        class: labo\Bundle\TestmanuBundle\services\fixturesLoader\fixturesLoader
        arguments: [@service_container, @templating]


    ###################################
    ### ELEMENTS DE FORMULAIRES
    ###################################

    # Éléments de formulaires personnalisés
    form.type.datepicker:
        class: labo\Bundle\TestmanuBundle\Form\Type\DatepickerType
        arguments:
            - "%formatDate%"
        tags:
            - { name: form.type, alias: datepicker }

    form.type.datepicker2:
        class: labo\Bundle\TestmanuBundle\Form\Type\Datepicker2Type
        arguments:
            - "%formatDate%"
        tags:
            - { name: form.type, alias: datepicker2 }

    form.type.datepicker2alldates:
        class: labo\Bundle\TestmanuBundle\Form\Type\Datepicker2alldatesType
        arguments:
            - "%formatDate%"
        tags:
            - { name: form.type, alias: datepicker2alldates }

    form.type.richtext:
        class: labo\Bundle\TestmanuBundle\Form\Type\richtextType
        tags:
            - { name: form.type, alias: richtext }

    form.type.gender:
        class: labo\Bundle\TestmanuBundle\Form\Type\GenderType
        tags:
            - { name: form.type, alias: gender }

    form.type.routes:
        class: labo\Bundle\TestmanuBundle\Form\Type\RoutesType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: routes }



