<?php

namespace AcmeGroup\LaboBundle\Entity;

// use AcmeGroup\LaboBundle\Entity\baseRepository;
use labo\Bundle\TestmanuBundle\Entity\bonLivraisonRepository as bonLivraisonBaseRepo;

/**
 * bonLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class bonLivraisonRepository extends bonLivraisonBaseRepo {


}