<?php

namespace AcmeGroup\LaboBundle\Entity;

// use AcmeGroup\LaboBundle\Entity\baseRepository;
use labo\Bundle\TestmanuBundle\Entity\versionRepository as versionBaseRepo;

/**
 * versionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class versionRepository extends versionBaseRepo {


}
