parameters:
#    acme_user.example.class: AcmeGroup\UserBundle\Example

services:
    acmegroup_user.registration.form.type:
        class: AcmeGroup\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acmegroup_user_registration }

    acmegroup_user.registrationPopup.form.type:
        class: AcmeGroup\UserBundle\Form\Type\RegistrationFormPopupType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: acmegroup_user_registration_popup }

    acmegroup.user.profile.form.type:
        class: AcmeGroup\UserBundle\Form\Type\ProfileFormType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: acmegroup_user_profile }

    # acmegroup.registration_popup.form.factory:
    #     class: FOS\UserBundle\Form\Factory\FormFactory
    #     arguments: 
    #      - { type: service, id: form.factory }
    #      - [%fos_user.registration.form.name%]
    #      - [%acmegroup.registration_popup.form.type%]
    #      - [%fos_user.registration.form.validation_groups%]

    # acmegroup.registration_popup.form.type:
    #     class: FOS\UserBundle\Form\Type\RegistrationFormPopupType
    #     arguments: [%fos_user.model.user.class%]
    #     tags:
    #         - { name: form.type, alias: fos_user_registration }

    ###################################
    ### ELEMENTS DE FORMULAIRES
    ###################################

    # Éléments de formulaires personnalisés
    form.type.datepicker:
        class: labo\Bundle\TestmanuBundle\Form\Type\DatepickerType
        arguments:
            - "%formatDate%"
        tags:
            - { name: form.type, alias: datepicker }

    form.type.datepicker2:
        class: labo\Bundle\TestmanuBundle\Form\Type\Datepicker2Type
        arguments:
            - "%formatDate%"
        tags:
            - { name: form.type, alias: datepicker2 }

    form.type.datepicker2alldates:
        class: labo\Bundle\TestmanuBundle\Form\Type\Datepicker2alldatesType
        arguments:
            - "%formatDate%"
        tags:
            - { name: form.type, alias: datepicker2alldates }

    form.type.richtext:
        class: labo\Bundle\TestmanuBundle\Form\Type\richtextType
        tags:
            - { name: form.type, alias: richtext }

    form.type.gender:
        class: labo\Bundle\TestmanuBundle\Form\Type\GenderType
        tags:
            - { name: form.type, alias: gender }

    form.type.routes:
        class: labo\Bundle\TestmanuBundle\Form\Type\RoutesType
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: routes }



